### ISSUE TITLE
Reproduceable example for gantt

### ISSUE THREAD

**Issue by JakeWritesCode** [highcharts/highcharts-svelte#4]
Hi folks, I'm trying to integrate this library for use with Gantt charts, but I'm struggling to find a reproduceable example of some working code. 

I can get the basic chart working from the docs and i've been trying to piece together the easiest reproduceable example for a Gantt chart from the typing, general HighCharts docs etc. 

```
<script>
	import Highcharts from "highcharts";
	import { GanttChart } from '@highcharts/svelte';

	// Gantt chart options
	const options = {
		title: {
			text: 'Simple Gantt Chart'
		},

		xAxis: [{
			min: '2014-11-17',
			max: '2014-11-30'
		}],

		series: [{
			name: 'Project 1',
			data: [{
				name: 'Start prototype',
				start: '2014-11-18',
				end: '2014-11-25'
			}, {
				name: 'Develop',
				start: '2014-11-20',
				end: '2014-11-25'
			}, {
				name: 'Run acceptance tests',
				start: '2014-11-23',
				end: '2014-11-26'
			}, {
				name: 'Test prototype',
				start: '2014-11-27',
				end: '2014-11-29'
			}]
		}]
	};
</script>

<GanttChart {options} {Highcharts} />
```

But I get a `Uncaught (in promise) TypeError: import_gantt.default is not a function`, what am I missing here?

**Comment by jszuminski** [comment]
Thanks for reporting!

As you can see, it works here: https://stackblitz.com/edit/vitejs-vite-hfw9h6?file=src%2FApp.svelte

If you get an error, please create a reproducible example online so that I can investigate.
